# Generated by Django 3.0 on 2020-02-06 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=40)),
                ('userAccount', models.CharField(max_length=40)),
                ('salt', models.CharField(max_length=40)),
                ('token', models.CharField(max_length=40)),
                ('userCookies', models.CharField(max_length=16)),
                ('admission', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='bookMarkArtwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artwork.Artwork')),
            ],
        ),
        migrations.CreateModel(
            name='bookMarkArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
            ],
        ),
    ]
