# Generated by Django 3.0 on 2020-02-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pixivPassword',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
