# Generated by Django 3.0 on 2020-02-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_pixivpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userId',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
