# Generated by Django 3.0 on 2020-02-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_updatecollections'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkartwork',
            name='order',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='workMark',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
