# Generated by Django 3.0 on 2019-12-26 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranklist', '0002_auto_20191224_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankwork',
            name='artistid',
        ),
    ]
