# Generated by Django 3.0 on 2019-12-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranklist', '0003_remove_rankwork_artistid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankwork',
            name='artistid',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
