# Generated by Django 3.0 on 2019-12-28 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranklist', '0004_rankwork_artistid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankwork',
            name='authurl',
        ),
        migrations.RemoveField(
            model_name='rankwork',
            name='picurl',
        ),
    ]
