# Generated by Django 3.0 on 2019-12-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picid', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Artist', models.CharField(max_length=40)),
                ('ArtistId', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Name', models.CharField(max_length=40)),
                ('Dictory', models.CharField(max_length=80)),
            ],
        ),
    ]
