# Generated by Django 3.0.1 on 2020-01-16 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picid', models.DecimalField(decimal_places=0, max_digits=10)),
                ('name', models.CharField(max_length=40)),
                ('url', models.CharField(max_length=25)),
                ('pageCount', models.DecimalField(decimal_places=0, max_digits=2)),
                ('imgformat', models.IntegerField(choices=[(0, 'jpg'), (1, 'png')])),
                ('picartist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
            ],
        ),
    ]
