# Generated by Django 3.0 on 2019-12-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='Dictory',
            field=models.CharField(max_length=100),
        ),
    ]
