# Generated by Django 3.0 on 2019-12-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_artwork_quality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='Dictory',
            new_name='Url',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='Quality',
        ),
    ]
