# Generated by Django 3.0 on 2019-12-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_auto_20191227_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='Artist',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='ArtistId',
            new_name='artistId',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='Picid',
            new_name='picid',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='Url',
            new_name='url',
        ),
    ]
