# Generated by Django 3.0 on 2019-12-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0005_auto_20191227_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='pageCount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
