# Generated by Django 3.0 on 2019-12-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0006_artwork_pagecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='url',
            field=models.CharField(max_length=25),
        ),
    ]
