# Generated by Django 3.0 on 2020-01-01 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
        ('artwork', '0008_artwork_imgformat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='artistId',
        ),
        migrations.AddField(
            model_name='artwork',
            name='picartist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='artist.Artist'),
            preserve_default=False,
        ),
    ]
